# SPDX-FileCopyrightText: 2026 mmayhew
# SPDX-License-Identifier: AGPL-3.0-only

"""Report Markdown and HTML rendering helpers."""

from __future__ import annotations

from collections.abc import Mapping

from datetime import datetime, timezone
from typing import Any

from config import APP_VERSION, PROJECT_NAME, resolve_effective_cfg
from services.projects.package_rendering import _PACKAGE_JINJA

from .composition import compose_report_context


_REPORT_HTML_TEMPLATE = _PACKAGE_JINJA.from_string("""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="darklab-report-format" content="1">
<title>{{ title }}</title>
<style>
body { color: #17202a; font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 0; }
.report-shell { max-width: 960px; margin: 0 auto; padding: 40px 28px 64px; }
.report-generated {
  color: #667381;
  display: flex;
  flex-wrap: wrap;
  font-size: 12px;
  gap: 6px;
  justify-content: flex-end;
  margin: 0 0 18px;
}
h1 { font-size: 32px; line-height: 1.15; margin: 0 0 10px; }
h2 { border-bottom: 1px solid #d9e1e8; font-size: 22px; margin: 34px 0 14px; padding-bottom: 7px; }
h3 { font-size: 16px; margin: 18px 0 8px; }
p { margin: 0 0 10px; }
table { border-collapse: collapse; margin: 12px 0 18px; width: 100%; }
th, td { border: 1px solid #d9e1e8; padding: 8px 10px; text-align: left; vertical-align: top; }
th { background: #f5f8fb; font-weight: 650; }
code, pre { font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace; }
pre { background: #f7f9fb; border: 1px solid #d9e1e8; overflow-wrap: anywhere; padding: 12px; white-space: pre-wrap; }
.muted { color: #667381; }
.meta-grid { display: grid; gap: 8px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); margin: 18px 0; }
.meta-item { border: 1px solid #d9e1e8; padding: 10px; }
.meta-label { color: #667381; display: block; font-size: 12px; text-transform: uppercase; }
@media print {
  body { color: #111; }
  .report-shell { max-width: none; padding: 0; }
  h2 { break-after: avoid; }
  table, pre { break-inside: avoid; }
}
</style>
</head>
<body>
<main class="report-shell">
<div class="report-generated">
<span>Generated by {{ generation.app_name }}{% if generation.version %} v{{ generation.version }}{% endif %}</span>
<span>· {{ generation.generated_at_display }}</span>
<span>· {{ generation.redaction_label }}</span>
</div>
<h1>{{ title }}</h1>
{% for section in sections %}
{% if section.enabled %}
<section data-report-section="{{ section.type }}">
<h2>{{ section.title }}</h2>
{% if section.type == "cover" %}
<div class="meta-grid">
{% for item in metadata_items %}
<div class="meta-item"><span class="meta-label">{{ item.label }}</span>{{ item.value }}</div>
{% endfor %}
</div>
{% if project.description %}<p>{{ project.description }}</p>{% endif %}
{% if draft.metadata.cover_notes %}<p>{{ draft.metadata.cover_notes }}</p>{% endif %}
{% elif section.type == "executive_summary" %}
{% if draft.metadata.executive_summary %}
<p>{{ draft.metadata.executive_summary }}</p>
{% else %}
<p class="muted">No executive summary has been written yet.</p>
{% endif %}
{% elif section.type == "scope_targets" %}
{% if targets %}
<table><thead><tr><th>Type</th><th>Target</th><th>Status</th><th>Source</th></tr></thead><tbody>
{% for target in targets %}
<tr>
<td>{{ target.type }}</td>
<td>{{ target.value or target.canonical_value }}</td>
<td>{{ target.review_state or target.status }}</td>
<td>{{ target.source }}</td>
</tr>
{% endfor %}
</tbody></table>
{% else %}<p class="muted">No targets are selected for this report.</p>{% endif %}
{% elif section.type == "methodology" %}
{% if draft.metadata.methodology %}
<p>{{ draft.metadata.methodology }}</p>
{% else %}
<p class="muted">No methodology narrative has been written yet.</p>
{% endif %}
{% if assessment_context %}
<h3>Assessment coverage</h3>
<p><strong>{{ assessment_context.assessment.title }}</strong> · {{ assessment_context.assessment.status }} ·
{{ assessment_context.rollup.covered_checks }} of \
{{ assessment_context.methodology.applicable_denominator }} applicable checks covered</p>
<p>{{ assessment_context.methodology.summary }}</p>
<table><thead><tr><th>State</th><th>Count</th></tr></thead><tbody>
<tr><td>Covered</td><td>{{ assessment_context.rollup.covered_checks }}</td></tr>
<tr><td>Awaiting review</td><td>{{ assessment_context.rollup.checks_awaiting_review }}</td></tr>
<tr><td>Untested</td><td>{{ assessment_context.rollup.untested_checks }}</td></tr>
<tr><td>Excluded</td><td>{{ assessment_context.rollup.excluded_checks }}</td></tr>
<tr><td>Unavailable evidence</td><td>{{ assessment_context.rollup.unavailable_evidence_checks }}</td></tr>
</tbody></table>
{% if assessment_context.manual_exclusions %}
<h3>Manual exclusions</h3>
<table><thead><tr><th>Check</th><th>Target</th><th>State</th><th>Reason</th></tr></thead><tbody>
{% for item in assessment_context.manual_exclusions %}
<tr><td><code>{{ item.check_id }}</code></td><td>{{ item.target_value }}</td>
<td>{{ item.state|replace("_", " ") }}</td><td>{{ item.reason }}</td></tr>
{% endfor %}
</tbody></table>
{% endif %}
{% if assessment_context.unavailable_evidence_warnings or assessment_context.screenshot_warnings %}
<h3>Coverage warnings</h3><ul>
{% for item in assessment_context.unavailable_evidence_warnings %}
<li><code>{{ item.check_id }}</code>: {{ item.reason }}</li>{% endfor %}
{% for item in assessment_context.screenshot_warnings %}
<li><code>{{ item.artifact_id }}</code>: {{ item.reason }}</li>{% endfor %}
</ul>
{% endif %}
{% endif %}
{% elif section.type == "findings_by_severity" %}
{% if assessment_context and assessment_context.fix_first["items"] %}
<h3>Fix first</h3>
<table><thead><tr><th>Remediation</th><th>Signals</th><th>Observations</th></tr></thead><tbody>
{% for item in assessment_context.fix_first["items"] %}
<tr><td>{{ item.title }}<br><code>{{ item.remediation_id }}</code></td>
<td>{% for reason in item.risk.priority_reasons %}{{ reason }}{% if not loop.last %}; {% endif %}{% endfor %}</td>
<td>{{ item.observation_count }} observations · {{ item.evidence_count }} evidence sources</td></tr>
{% endfor %}
</tbody></table>
{% endif %}
{% if assessment_finding_changes %}
<h3>Assessment finding changes</h3>
<p><strong>{{ assessment_finding_changes.assessment.title }}</strong> ·
{{ assessment_finding_changes.comparison.comparable_checks }} of
{{ assessment_finding_changes.comparison.total_checks }} checks comparable</p>
<table><thead><tr>
<th>State</th><th>Remediation</th><th>Current finding / evidence</th>
<th>Earlier finding / evidence</th><th>Comparison reason</th>
</tr></thead><tbody>
{% for item in assessment_finding_changes["items"] %}
<tr>
<td>{{ item.state|replace("_", " ") }}</td>
<td>{{ item.vulnerability_id or item.rule_identity }}<br><code>{{ item.remediation_id }}</code></td>
<td>
{% for finding in item.current_findings %}{{ finding.title }} (<code>{{ finding.id }}</code>)<br>{% endfor %}
{% for evidence_id in item.current_evidence_ids %}<code>{{ evidence_id }}</code><br>{% endfor %}
{% if not item.current_findings and not item.current_evidence_ids %}<span class="muted">None</span>{% endif %}
</td>
<td>
{% for finding in item.previous_findings %}{{ finding.title }} (<code>{{ finding.id }}</code>)<br>{% endfor %}
{% for evidence_id in item.previous_evidence_ids %}<code>{{ evidence_id }}</code><br>{% endfor %}
{% if not item.previous_findings and not item.previous_evidence_ids %}<span class="muted">None</span>{% endif %}
</td>
<td>{% if item.reasons %}{{ item.reasons|join("; ") }}{% else %}<span class="muted">No exception recorded</span>{% endif %}</td>
</tr>
{% endfor %}
</tbody></table>
<p class="muted">Counts and rows represent distinct remediation groups, not evidence observations.</p>
{% endif %}
{% if findings_by_severity %}
{% for group in findings_by_severity %}
<h3>{{ group.severity|title }} ({{ group.count }})</h3>
<table><thead><tr><th>Finding</th><th>Target</th><th>Review</th><th>Remediation / verification</th></tr></thead><tbody>
{% for finding in group.findings %}
<tr>
<td>{{ finding.title or finding.raw_line or finding.id }}</td>
<td>
{% if finding.target_references %}
{% for target in finding.target_references %}
<p>
<strong>{{ target.type }}:</strong> {{ target.value or target.target_id }}
{% if target.relationship_source %}
<br><span class="muted">{{ target.relationship_source }}
{% if target.source_run_id %} - run {{ target.source_run_id }}{% endif %}
</span>
{% endif %}
</p>
{% endfor %}
{% else %}
{{ finding.target_id or finding.entity_id }}
{% endif %}
</td>
<td>{{ finding.review_state or finding.status }}</td>
<td>
{% if finding.risk and finding.risk.priority_reasons %}
<p><strong>Priority:</strong> {{ finding.risk.priority_reasons|join("; ") }}</p>
{% endif %}
{% if finding.triage %}
{% if finding.triage.remediation %}<p><strong>Remediation:</strong> {{ finding.triage.remediation }}</p>{% endif %}
{% if finding.triage.verification_status and finding.triage.verification_status != "not_started" %}
<p><strong>Verification:</strong> {{ finding.triage.verification_status }}</p>
{% endif %}
{% if finding.triage.verification_steps %}<p><strong>Steps:</strong> {{ finding.triage.verification_steps }}</p>{% endif %}
{% if finding.triage.verification_notes %}
<p><strong>Private notes:</strong> {{ finding.triage.verification_notes }}</p>
{% endif %}
{% else %}<span class="muted">No remediation details recorded.</span>{% endif %}
</td>
</tr>
{% endfor %}
</tbody></table>
{% endfor %}
{% else %}<p class="muted">No findings are selected for this report.</p>{% endif %}
{% elif section.type == "included_runs" %}
{% if runs %}
<table><thead><tr><th>Command</th><th>Started</th><th>Exit</th><th>Lines</th></tr></thead><tbody>
{% for run in runs %}
<tr>
<td><code>{{ run.command or run.id }}</code></td>
<td>{{ run.started }}</td>
<td>{{ run.exit_code }}</td>
<td>{{ run.output_line_count }}</td>
</tr>
{% endfor %}
</tbody></table>
{% else %}<p class="muted">No runs are selected for this report.</p>{% endif %}
{% elif section.type == "artifacts" %}
{% if artifacts %}
{% for artifact in artifacts %}
<h3>{{ artifact.display_name or artifact.workspace_path or artifact.id }}</h3>
<p class="muted">
{{ artifact.kind }}{% if artifact.byte_size %} · {{ artifact.byte_size }} bytes{% endif %}
{% if artifact.run_id %} · run {{ artifact.run_id }}{% endif %}
</p>
{% if artifact.report_preview.embedded %}
<pre>{{ artifact.report_preview.text }}</pre>
{% else %}
<p class="muted">{{ artifact.report_preview.reason }}</p>
{% endif %}
{% endfor %}
{% else %}<p class="muted">No artifacts are selected for this report.</p>{% endif %}
{% elif section.type == "appendix" %}
<table><tbody>
<tr><th>Runs</th><td>{{ counts.runs }}</td></tr>
<tr><th>Targets</th><td>{{ counts.targets }}</td></tr>
<tr><th>Findings</th><td>{{ counts.findings }}</td></tr>
<tr><th>Artifacts</th><td>{{ counts.artifacts }}</td></tr>
</tbody></table>
{% if artifact_warnings %}
<h3>Artifact notes</h3>
<ul>{% for warning in artifact_warnings %}<li>{{ warning.label }}: {{ warning.reason }}</li>{% endfor %}</ul>
{% endif %}
{% endif %}
</section>
{% endif %}
{% endfor %}
{% if cve_risk_snapshot %}
<section data-report-section="cve-risk-sources">
<h2>CVE risk data sources</h2>
{% for source in cve_risk_snapshot.sources %}
<p><strong>{{ source.source|upper }}</strong> — {{ source.attribution }}<br>
<span class="muted">Origin {{ source.origin or "unavailable" }};
version {{ source.source_version or "unavailable" }};
model {{ source.model_version or "unavailable" }};
published {{ source.published_at or "unknown" }};
fetched {{ source.retrieved_at or "unknown" }};
status {{ source.status or "unavailable" }};
checksum {{ source.checksum_sha256 or "unavailable" }}.</span></p>
{% endfor %}
<p class="muted">{{ cve_risk_snapshot.non_endorsement }}</p>
</section>
{% endif %}
</main>
</body>
</html>
""")


def _metadata_items(context: dict[str, Any]) -> list[dict[str, str]]:
    draft = context.get("draft") if isinstance(context, dict) else {}
    metadata = draft.get("metadata") if isinstance(draft, dict) else {}
    project = context.get("project") if isinstance(context, dict) else {}
    raw_items = [
        ("Project", (project or {}).get("name") or ""),
        ("Engagement", (metadata or {}).get("engagement_name") or ""),
        ("Date range", (metadata or {}).get("date_range") or ""),
        ("Operator", (metadata or {}).get("operator") or ""),
        ("Client", (metadata or {}).get("client") or ""),
        ("Contact", (metadata or {}).get("contact") or ""),
    ]
    return [{"label": label, "value": str(value)} for label, value in raw_items if str(value or "").strip()]


def _iso_generated_at(value: datetime | str | None = None) -> str:
    if isinstance(value, datetime):
        candidate = value if value.tzinfo else value.replace(tzinfo=timezone.utc)
        return candidate.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    if isinstance(value, str) and value.strip():
        return value.strip()
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def report_generation_metadata(
    context: dict[str, Any],
    *,
    generated_at: datetime | str | None = None,
    cfg: Mapping[str, Any] | None = None,
) -> dict[str, str]:
    active_cfg = resolve_effective_cfg(cfg)
    app_name = str(active_cfg.get("app_name") or PROJECT_NAME or "darklab_shell")
    version = str(APP_VERSION or "").strip()
    export = context.get("export") if isinstance(context, dict) else {}
    redaction_mode = str((export or {}).get("redaction_mode") or "redacted").strip().lower()
    redaction_mode = "raw" if redaction_mode == "raw" else "redacted"
    redaction_label = "Raw" if redaction_mode == "raw" else "Redacted"
    generated_at_iso = _iso_generated_at(generated_at)
    generated_at_display = generated_at_iso.replace("T", " ").replace("Z", " UTC")
    return {
        "app_name": app_name,
        "version": version,
        "generated_at": generated_at_iso,
        "generated_at_display": generated_at_display,
        "redaction_mode": redaction_mode,
        "redaction_label": redaction_label,
    }


def _generation_line(generation: dict[str, str]) -> str:
    version = f" v{generation.get('version')}" if generation.get("version") else ""
    return (
        f"Generated by {generation.get('app_name')}{version}"
        f" · {generation.get('generated_at_display')}"
        f" · {generation.get('redaction_label')}"
    )


def report_title(context: dict[str, Any]) -> str:
    draft = context.get("draft") if isinstance(context, dict) else {}
    metadata = draft.get("metadata") if isinstance(draft, dict) else {}
    title = str((metadata or {}).get("engagement_name") or "").strip()
    return title or "Engagement Report"


def _md(value: Any) -> str:
    return str(value or "").replace("\r\n", "\n").replace("\r", "\n").strip()


def _md_code(value: Any) -> str:
    text = _md(value).replace("`", "\\`")
    return f"`{text}`" if text else ""


def _md_table_cell(value: Any) -> str:
    return _md(value).replace("\n", " ").replace("\\", "\\\\").replace("|", "\\|")


def _markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    if not rows:
        return []
    lines = [
        "| " + " | ".join(_md_table_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_md_table_cell(item) for item in row) + " |")
    return lines


def _append_assessment_finding_changes_markdown(
    lines: list[str],
    context: dict[str, Any],
) -> None:
    changes = context.get("assessment_finding_changes")
    if not isinstance(changes, dict):
        return
    raw_assessment = changes.get("assessment")
    raw_comparison = changes.get("comparison")
    assessment = raw_assessment if isinstance(raw_assessment, dict) else {}
    comparison = raw_comparison if isinstance(raw_comparison, dict) else {}
    lines.extend([
        "### Assessment finding changes",
        "",
        f"- Cycle: {_md(assessment.get('title') or assessment.get('id'))}",
        "- Comparison: "
        f"{int(comparison.get('comparable_checks') or 0)} of "
        f"{int(comparison.get('total_checks') or 0)} checks comparable",
        "- Counts and rows represent distinct remediation groups, not evidence observations.",
    ])
    for item in changes.get("items", []):
        if not isinstance(item, dict):
            continue
        label = item.get("vulnerability_id") or item.get("rule_identity") or "Saved remediation"
        lines.extend(("", f"#### {_md(label)}", ""))
        lines.append(f"- State: {_md(str(item.get('state') or 'incomparable').replace('_', ' '))}")
        lines.append(f"- Remediation: {_md_code(item.get('remediation_id'))}")
        for side, side_label in (("current", "Current"), ("previous", "Earlier")):
            references = [
                f"{_md(finding.get('title') or finding.get('id'))} ({_md_code(finding.get('id'))})"
                for finding in item.get(f"{side}_findings", [])
                if isinstance(finding, dict)
            ]
            references.extend(
                _md_code(value)
                for value in item.get(f"{side}_evidence_ids", [])
                if str(value or "")
            )
            lines.append(f"- {side_label}: {', '.join(references) if references else 'None'}")
        reasons = "; ".join(str(value) for value in item.get("reasons", []) if str(value or ""))
        lines.append(f"- Comparison reason: {_md(reasons or 'No exception recorded')}")
    lines.append("")


def _append_assessment_context_markdown(
    lines: list[str],
    context: dict[str, Any],
) -> None:
    raw = context.get("assessment_context")
    if not isinstance(raw, dict):
        return
    assessment = raw.get("assessment") if isinstance(raw.get("assessment"), dict) else {}
    rollup = raw.get("rollup") if isinstance(raw.get("rollup"), dict) else {}
    methodology = raw.get("methodology") if isinstance(raw.get("methodology"), dict) else {}
    lines.extend([
        "",
        "### Assessment coverage",
        "",
        f"- Cycle: {_md(assessment.get('title') or assessment.get('id'))}",
        f"- Status: {_md(assessment.get('status'))}",
        f"- Applicable denominator: {int(methodology.get('applicable_denominator') or 0)}",
        f"- Covered: {int(rollup.get('covered_checks') or 0)}",
        f"- Awaiting review: {int(rollup.get('checks_awaiting_review') or 0)}",
        f"- Untested: {int(rollup.get('untested_checks') or 0)}",
        f"- Excluded: {int(rollup.get('excluded_checks') or 0)}",
        f"- Unavailable evidence: {int(rollup.get('unavailable_evidence_checks') or 0)}",
        "",
        _md(methodology.get("summary")),
    ])
    exclusions = raw.get("manual_exclusions") if isinstance(raw.get("manual_exclusions"), list) else []
    if exclusions:
        lines.extend(("", "#### Manual exclusions", ""))
        lines.extend(_markdown_table(
            ["Check", "Target", "State", "Reason"],
            [[
                item.get("check_id"), item.get("target_value"),
                str(item.get("state") or "").replace("_", " "), item.get("reason"),
            ] for item in exclusions if isinstance(item, dict)],
        ))
    warnings = [
        *[item for item in raw.get("unavailable_evidence_warnings", []) if isinstance(item, dict)],
        *[item for item in raw.get("screenshot_warnings", []) if isinstance(item, dict)],
    ]
    if warnings:
        lines.extend(("", "#### Coverage warnings", ""))
        lines.extend(
            f"- {_md_code(item.get('check_id') or item.get('artifact_id'))}: {_md(item.get('reason'))}"
            for item in warnings
        )
    lines.append("")


def _append_fix_first_markdown(lines: list[str], context: dict[str, Any]) -> None:
    raw = context.get("assessment_context")
    fix_first = raw.get("fix_first") if isinstance(raw, dict) else None
    items = fix_first.get("items") if isinstance(fix_first, dict) else None
    if not isinstance(items, list) or not items:
        return
    lines.extend(("### Fix first", ""))
    for item in items:
        if not isinstance(item, dict):
            continue
        risk = item.get("risk") if isinstance(item.get("risk"), dict) else {}
        reasons = risk.get("priority_reasons") if isinstance(risk.get("priority_reasons"), list) else []
        lines.extend([
            f"#### {_md(item.get('title') or item.get('remediation_id'))}",
            "",
            f"- Remediation: {_md_code(item.get('remediation_id'))}",
            f"- Signals: {_md('; '.join(str(reason) for reason in reasons) or 'No stored CVE-risk signals')}",
            f"- Evidence: {int(item.get('observation_count') or 0)} observations, "
            f"{int(item.get('evidence_count') or 0)} evidence sources",
            "",
        ])


def _target_reference_label(reference: Any) -> str:
    if not isinstance(reference, dict):
        return ""
    target_type = _md(reference.get("type") or "target")
    value = _md(reference.get("value") or reference.get("target_id"))
    source = _md(reference.get("relationship_source"))
    source_run = _md(reference.get("source_run_id"))
    label = f"{target_type}: {value}" if value else target_type
    details = [item for item in (source, f"run {source_run}" if source_run else "") if item]
    return f"{label} ({', '.join(details)})" if details else label


def _finding_target_labels(finding: dict[str, Any]) -> list[str]:
    references = finding.get("target_references")
    labels = [
        _target_reference_label(reference)
        for reference in references
        if isinstance(reference, dict)
    ] if isinstance(references, list) else []
    labels = [label for label in labels if label]
    if labels:
        return labels
    target_id = _md(finding.get("target_id") or finding.get("entity_id"))
    return [target_id] if target_id else []


def _section_enabled(section: dict[str, Any]) -> bool:
    return bool(section.get("enabled", True))


def _render_markdown_section(section: dict[str, Any], context: dict[str, Any]) -> list[str]:
    section_type = str(section.get("type") or "")
    lines = [f"## {_md(section.get('title'))}", ""]
    draft = context["draft"]
    metadata = draft.get("metadata") or {}
    if section_type == "cover":
        for item in _metadata_items(context):
            lines.append(f"- **{item['label']}:** {item['value']}")
        project_description = _md((context.get("project") or {}).get("description"))
        cover_notes = _md(metadata.get("cover_notes"))
        if project_description:
            lines.extend(("", project_description))
        if cover_notes:
            lines.extend(("", cover_notes))
    elif section_type == "executive_summary":
        lines.append(_md(metadata.get("executive_summary")) or "_No executive summary has been written yet._")
    elif section_type == "scope_targets":
        rows = [
            [
                target.get("type"),
                target.get("value") or target.get("canonical_value"),
                target.get("review_state") or target.get("status"),
                target.get("source"),
            ]
            for target in context.get("targets", [])
        ]
        target_table = _markdown_table(["Type", "Target", "Status", "Source"], rows)
        lines.extend(target_table or ["_No targets are selected for this report._"])
    elif section_type == "methodology":
        lines.append(_md(metadata.get("methodology")) or "_No methodology narrative has been written yet._")
        _append_assessment_context_markdown(lines, context)
    elif section_type == "findings_by_severity":
        _append_fix_first_markdown(lines, context)
        _append_assessment_finding_changes_markdown(lines, context)
        if not context.get("findings_by_severity"):
            lines.append("_No findings are selected for this report._")
        for group in context.get("findings_by_severity", []):
            lines.extend((f"### {str(group.get('severity') or '').title()} ({group.get('count')})", ""))
            for finding in group.get("findings", []):
                lines.append(f"- **{_md(finding.get('title') or finding.get('raw_line') or finding.get('id'))}**")
                details = [
                    ("Target", "; ".join(_finding_target_labels(finding))),
                    ("Review", finding.get("review_state") or finding.get("status")),
                    ("Run", finding.get("run_id")),
                ]
                for label, value in details:
                    if _md(value):
                        lines.append(f"  - {label}: {_md(value)}")
                risk = finding.get("risk") if isinstance(finding.get("risk"), dict) else {}
                reasons = risk.get("priority_reasons") if isinstance(risk.get("priority_reasons"), list) else []
                if reasons:
                    lines.append(f"  - Priority: {_md('; '.join(str(reason) for reason in reasons))}")
                triage = finding.get("triage") if isinstance(finding.get("triage"), dict) else {}
                for label, key in (
                    ("Remediation", "remediation"),
                    ("Verification", "verification_status"),
                    ("Verification steps", "verification_steps"),
                    ("Private notes", "verification_notes"),
                ):
                    if _md(triage.get(key)):
                        lines.append(f"  - {label}: {_md(triage.get(key))}")
    elif section_type == "included_runs":
        rows = [
            [
                run.get("command") or run.get("id"),
                run.get("started"),
                run.get("exit_code"),
                run.get("output_line_count"),
            ]
            for run in context.get("runs", [])
        ]
        run_table = _markdown_table(["Command", "Started", "Exit", "Lines"], rows)
        lines.extend(run_table or ["_No runs are selected for this report._"])
    elif section_type == "artifacts":
        if not context.get("artifacts"):
            lines.append("_No artifacts are selected for this report._")
        for artifact in context.get("artifacts", []):
            label = artifact.get("display_name") or artifact.get("workspace_path") or artifact.get("id")
            lines.extend((f"### {_md(label)}", ""))
            lines.append(f"- Kind: {_md(artifact.get('kind'))}")
            if artifact.get("byte_size"):
                lines.append(f"- Size: {artifact.get('byte_size')} bytes")
            preview = artifact.get("report_preview") if isinstance(artifact.get("report_preview"), dict) else {}
            if preview.get("embedded"):
                lines.extend(("", "```text", str(preview.get("text") or "").rstrip(), "```"))
            else:
                lines.append(f"- Listed only: {_md(preview.get('reason'))}")
    elif section_type == "appendix":
        raw_counts = context.get("counts")
        counts = raw_counts if isinstance(raw_counts, dict) else {}
        lines.extend(_markdown_table(["Item", "Count"], [[key.title(), value] for key, value in counts.items()]))
        warnings = context.get("artifact_warnings") if isinstance(context.get("artifact_warnings"), list) else []
        if warnings:
            lines.extend(("", "### Artifact notes", ""))
            for warning in warnings:
                lines.append(f"- {_md(warning.get('label'))}: {_md(warning.get('reason'))}")
    return lines


def render_report_markdown(
    draft: dict[str, Any] | None,
    *,
    project: dict[str, Any] | None = None,
    session_id: str = "",
    project_id: str = "",
    team_id: str = "",
    cfg: Mapping[str, Any] | None = None,
    generated_at: datetime | str | None = None,
) -> str:
    context = compose_report_context(
        draft,
        project=project,
        session_id=session_id,
        project_id=project_id,
        team_id=team_id,
        cfg=cfg,
    )
    return render_report_markdown_from_context(context, generated_at=generated_at, cfg=cfg)


def render_report_markdown_from_context(
    context: dict[str, Any],
    *,
    generated_at: datetime | str | None = None,
    cfg: Mapping[str, Any] | None = None,
) -> str:
    title = report_title(context)
    generation = report_generation_metadata(context, generated_at=generated_at, cfg=cfg)
    lines = [f"# {title}", "", f"_{_generation_line(generation)}_", ""]
    for section in context["draft"]["sections"]:
        if _section_enabled(section):
            lines.extend(_render_markdown_section(section, context))
            lines.append("")
    snapshot = context.get("cve_risk_snapshot")
    if isinstance(snapshot, dict) and snapshot:
        lines.extend(("## CVE risk data sources", ""))
        for source in snapshot.get("sources", []):
            lines.append(
                f"- **{_md(str(source.get('source') or '').upper())}:** "
                f"{_md(source.get('attribution'))}; origin {_md(source.get('origin') or 'unavailable')}; "
                f"version {_md(source.get('source_version') or 'unavailable')}; "
                f"model {_md(source.get('model_version') or 'unavailable')}; "
                f"published {_md(source.get('published_at') or 'unknown')}; "
                f"fetched {_md(source.get('retrieved_at') or 'unknown')}; "
                f"status {_md(source.get('status') or 'unavailable')}; "
                f"checksum {_md(source.get('checksum_sha256') or 'unavailable')}"
            )
        lines.extend(("", _md(snapshot.get("non_endorsement")), ""))
    return "\n".join(lines).rstrip() + "\n"


def render_report_html(
    draft: dict[str, Any] | None,
    *,
    project: dict[str, Any] | None = None,
    session_id: str = "",
    project_id: str = "",
    team_id: str = "",
    cfg: Mapping[str, Any] | None = None,
    generated_at: datetime | str | None = None,
) -> str:
    context = compose_report_context(
        draft,
        project=project,
        session_id=session_id,
        project_id=project_id,
        team_id=team_id,
        cfg=cfg,
    )
    return render_report_html_from_context(context, generated_at=generated_at, cfg=cfg)


def render_report_html_from_context(
    context: dict[str, Any],
    *,
    generated_at: datetime | str | None = None,
    cfg: Mapping[str, Any] | None = None,
) -> str:
    generation = report_generation_metadata(context, generated_at=generated_at, cfg=cfg)
    return _REPORT_HTML_TEMPLATE.render(
        title=report_title(context),
        generation=generation,
        sections=context["draft"]["sections"],
        draft=context["draft"],
        project=context.get("project") or {},
        metadata_items=_metadata_items(context),
        counts=context.get("counts") or {},
        runs=context.get("runs") or [],
        targets=context.get("targets") or [],
        findings_by_severity=context.get("findings_by_severity") or [],
        assessment_context=context.get("assessment_context") or {},
        assessment_finding_changes=context.get("assessment_finding_changes") or {},
        artifacts=context.get("artifacts") or [],
        artifact_warnings=context.get("artifact_warnings") or [],
        cve_risk_snapshot=context.get("cve_risk_snapshot") or {},
    )
