services:
  shell:
    build:
      context: ..
      dockerfile: Dockerfile
    image: shell-darklab
    container_name: shell-darklab
    ports:
      - "8888:8888"
    volumes:
      - ../app:/app:ro
      - ../data:/data
    tmpfs:
      - /tmp
    cap_add:
      - NET_RAW
      - NET_ADMIN
    read_only: true
    restart: unless-stopped
