# SPDX-FileCopyrightText: 2026 mmayhew
# SPDX-License-Identifier: AGPL-3.0-only

"""Schema migration registry.

The checked-in migration stream is the shared schema ledger for SQLite and
Postgres. Backend-specific statements keep SQLite FTS and Postgres trigram
schema explicit while startup routes both backends through the same runner.
"""

from .runner import Migration
from . import (
    baseline,
    v0001_postgres_baseline,
    v0002_postgres_run_search,
    v0003_postgres_atlas_search,
    v0004_postgres_atlas_detail_indexes,
    v0005_postgres_project_findings_indexes,
    v0006_postgres_atlas_suppression,
    v0007_postgres_atlas_metadata_search,
    v0008_postgres_session_token_last_seen,
    v0009_notification_channels,
    v0010_schedules,
    v0011_watchers,
    v0012_run_output_summary,
    v0013_ai_run_assists,
    v0014_ai_assist_progress,
    v0015_teams,
    v0016_team_scope_runs,
    v0017_team_scope_projects,
    v0018_team_scope_automation,
    v0019_team_scope_notifications,
    v0020_team_scope_ai_assists,
    v0021_team_scope_workflows,
    v0022_project_slug_scope,
    v0023_team_code_hash_uniqueness,
    v0024_team_scope_atlas,
    v0025_team_scope_workspace_metadata,
    v0026_project_auto_promote_rules,
    v0027_atlas_import_sources,
    v0028_finding_triage_details,
    v0029_project_reports,
    v0030_audit_events,
    v0031_run_output_summary_status,
    v0032_watcher_monitoring_phase0,
    v0033_watcher_monitoring_policy,
    v0034_project_digest_settings,
    v0035_project_digest_schedule_dispatch,
    v0036_atlas_port_entity_metadata,
    v0037_scan_target_observations,
    v0038_url_host_entity_links,
    v0039_unified_schema_baseline,
    v0040_personal_scope_team_id_normalization,
    v0041_project_atlas_sort_indexes,
    v0042_run_artifact_lookup_indexes,
    v0043_workflow_executions,
    v0044_finding_occurrence_comparison,
    v0045_atlas_entity_exact_lookup_index,
    v0046_cve_risk_intelligence,
    v0047_cve_advisory_intelligence,
    v0048_cve_risk_source_versions,
    v0049_project_assessments,
    v0050_assessment_check_actors,
    v0051_finding_provenance,
    v0052_finding_details,
    v0053_finding_remediation_dispositions,
    v0054_finding_remediation_guidance,
    v0055_finding_remediation_merges,
    v0056_finding_evidence_links,
    v0057_manual_findings,
    v0058_finding_verification_dispositions,
    v0059_assessment_finding_reconciliation,
    v0060_project_http_profiles,
    v0061_workflow_fanout_checkpoints,
)

_ = baseline

MIGRATIONS: tuple[Migration, ...] = (
    v0001_postgres_baseline.MIGRATION,
    v0002_postgres_run_search.MIGRATION,
    v0003_postgres_atlas_search.MIGRATION,
    v0004_postgres_atlas_detail_indexes.MIGRATION,
    v0005_postgres_project_findings_indexes.MIGRATION,
    v0006_postgres_atlas_suppression.MIGRATION,
    v0007_postgres_atlas_metadata_search.MIGRATION,
    v0008_postgres_session_token_last_seen.MIGRATION,
    v0009_notification_channels.MIGRATION,
    v0010_schedules.MIGRATION,
    v0011_watchers.MIGRATION,
    v0012_run_output_summary.MIGRATION,
    v0013_ai_run_assists.MIGRATION,
    v0014_ai_assist_progress.MIGRATION,
    v0015_teams.MIGRATION,
    v0016_team_scope_runs.MIGRATION,
    v0017_team_scope_projects.MIGRATION,
    v0018_team_scope_automation.MIGRATION,
    v0019_team_scope_notifications.MIGRATION,
    v0020_team_scope_ai_assists.MIGRATION,
    v0021_team_scope_workflows.MIGRATION,
    v0022_project_slug_scope.MIGRATION,
    v0023_team_code_hash_uniqueness.MIGRATION,
    v0024_team_scope_atlas.MIGRATION,
    v0025_team_scope_workspace_metadata.MIGRATION,
    v0026_project_auto_promote_rules.MIGRATION,
    v0027_atlas_import_sources.MIGRATION,
    v0028_finding_triage_details.MIGRATION,
    v0029_project_reports.MIGRATION,
    v0030_audit_events.MIGRATION,
    v0031_run_output_summary_status.MIGRATION,
    v0032_watcher_monitoring_phase0.MIGRATION,
    v0033_watcher_monitoring_policy.MIGRATION,
    v0034_project_digest_settings.MIGRATION,
    v0035_project_digest_schedule_dispatch.MIGRATION,
    v0036_atlas_port_entity_metadata.MIGRATION,
    v0037_scan_target_observations.MIGRATION,
    v0038_url_host_entity_links.MIGRATION,
    v0039_unified_schema_baseline.MIGRATION,
    v0040_personal_scope_team_id_normalization.MIGRATION,
    v0041_project_atlas_sort_indexes.MIGRATION,
    v0042_run_artifact_lookup_indexes.MIGRATION,
    v0043_workflow_executions.MIGRATION,
    v0044_finding_occurrence_comparison.MIGRATION,
    v0045_atlas_entity_exact_lookup_index.MIGRATION,
    v0046_cve_risk_intelligence.MIGRATION,
    v0047_cve_advisory_intelligence.MIGRATION,
    v0048_cve_risk_source_versions.MIGRATION,
    v0049_project_assessments.MIGRATION,
    v0050_assessment_check_actors.MIGRATION,
    v0051_finding_provenance.MIGRATION,
    v0052_finding_details.MIGRATION,
    v0053_finding_remediation_dispositions.MIGRATION,
    v0054_finding_remediation_guidance.MIGRATION,
    v0055_finding_remediation_merges.MIGRATION,
    v0056_finding_evidence_links.MIGRATION,
    v0057_manual_findings.MIGRATION,
    v0058_finding_verification_dispositions.MIGRATION,
    v0059_assessment_finding_reconciliation.MIGRATION,
    v0060_project_http_profiles.MIGRATION,
    v0061_workflow_fanout_checkpoints.MIGRATION,
)
