#!/usr/bin/env node
/**
 * Build vendor JS files from npm packages into app/static/js/vendor/.
 *
 * jspdf ships a UMD build that works as-is.
 * ansi_up v6+ is ESM-only, so we wrap it in an IIFE that exposes AnsiUp as a
 * browser global — the same interface all callers expect.
 *
 * Run via:  npm run vendor:sync
 */

import { readFileSync, writeFileSync, copyFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const args = process.argv.slice(2);
let VENDOR_DIR = resolve(ROOT, 'app/static/js/vendor');
for (let i = 0; i < args.length; i += 1) {
  if (args[i] === '--out-dir' && typeof args[i + 1] === 'string') {
    VENDOR_DIR = resolve(ROOT, args[i + 1]);
    i += 1;
  }
}
const NODE_MODULES = resolve(ROOT, 'node_modules');

// ── jspdf ─────────────────────────────────────────────────────────────────────
// The UMD build exposes window.jspdf and works without modification.
copyFileSync(
  resolve(NODE_MODULES, 'jspdf/dist/jspdf.umd.min.js'),
  resolve(VENDOR_DIR, 'jspdf.umd.min.js'),
);
console.log('✓ jspdf: copied UMD build');

// ── ansi_up ───────────────────────────────────────────────────────────────────
// v6+ ships ESM-only (export class AnsiUp). We strip the export keyword and
// wrap the module body in an IIFE that assigns AnsiUp to the global scope.
const esm = readFileSync(resolve(NODE_MODULES, 'ansi_up/ansi_up.js'), 'utf8');
const { version: ansiUpVersion } = JSON.parse(
  readFileSync(resolve(NODE_MODULES, 'ansi_up/package.json'), 'utf8'),
);
const body = esm
  .replace(/^"use strict";\n/, '')
  .replace('export class AnsiUp', 'class AnsiUp');
const wrapped = [
  `/* ansi_up v${ansiUpVersion} — UMD wrapper generated by scripts/build_vendor.mjs */`,
  '(function (global) {',
  '"use strict";',
  body,
  'global.AnsiUp = AnsiUp;',
  '})(typeof globalThis !== \'undefined\' ? globalThis : this);',
  '',
].join('\n');
writeFileSync(resolve(VENDOR_DIR, 'ansi_up.js'), wrapped);
console.log('✓ ansi_up: wrapped ESM as browser global');
