# SPDX-FileCopyrightText: 2026 mmayhew
# SPDX-License-Identifier: AGPL-3.0-only

"""
Evidence package rendering and export helpers.
"""

from __future__ import annotations

import gzip
import json
import logging
import re
from pathlib import PurePosixPath

from jinja2 import Environment, select_autoescape

from core.redaction import line_entries_from_events, redact_line_entries
from services.assessments.batch.provenance import (
    apply_assessment_batch_provenance,
    assessment_batch_provenance_by_run,
)
from services.history.permalinks import _font_face_css, _format_duration, _permalink_context
from services.projects.contracts import ProjectWorkspaceError
from services.projects.metadata import _metadata_owner_where
from services.projects.models import entity_note_body as _entity_note_body
from services.projects.packages import (
    redact_package_run as _redact_package_run,
    redact_package_value as _redact_package_value,
)
from services.projects.scope import shared_owner_where
from services.projects.utils import cfg_int as _cfg_int
from services.runs.output_model import LineKind, line_event_from_legacy, to_legacy_entry
from services.runs.output_store import load_full_output_entries


log = logging.getLogger("shell")
_PACKAGE_JINJA = Environment(
    autoescape=select_autoescape(default=True, default_for_string=True),
    trim_blocks=True,
    lstrip_blocks=True,
)

_PACKAGE_PAGE_TEMPLATE = _PACKAGE_JINJA.from_string("""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="darklab-package-format" content="1">
<title>{{ title }}</title>
{% if css_href -%}
<link rel="stylesheet" href="{{ css_href }}">
{% else -%}
<style>{{ inline_css | safe }}</style>
{% endif -%}
</head>
<body>
{{ body | safe }}
{{ script | safe }}
</body>
</html>
""")

_PACKAGE_RUN_TEMPLATE = _PACKAGE_JINJA.from_string("""
<main class="page">
<a href="../index.html">Back to package index</a>
<div class="topline">{{ project_name }} evidence package</div>
<h1>{{ title }}</h1>
<p class="subtitle mono">Run {{ run_id }} · generated {{ generated_at }}</p>
<section class="grid">
{% for item in metric_items -%}
<div class="metric">
<span>{{ item.kind }}</span>
<strong>{{ item.text }}</strong>
</div>
{% endfor -%}
</section>
<h2>Transcript</h2>
{% if transcript_text_path -%}
<p><a href="../{{ transcript_text_path }}">Download full text transcript</a></p>
{% endif -%}
<section class="transcript">
{% if lines -%}
{% for line in lines -%}
<div id="{{ line.id }}" class="{{ line.class_name }}">{{ line.text }}</div>
{% endfor -%}
{% else -%}
<div class="line muted">No output captured.</div>
{% endif -%}
</section>
<p class="footer">Generated by darklab shell evidence packages.</p>
</main>
""")

_PACKAGE_INDEX_TEMPLATE = _PACKAGE_JINJA.from_string("""
<main class="page">
<div class="topline">darklab shell evidence package</div>
<h1>{{ package_name }}</h1>
<p class="subtitle">{{ project_name }} · generated {{ generated_at }}</p>
<section class="grid">
{% for item in metrics -%}
<div class="metric">
<span>{{ item.label }}</span>
<strong>{{ item.count }}</strong>
</div>
{% endfor -%}
</section>
{% if project_notes -%}
<h2>Project Notes</h2>
<section class="card"><p>{{ project_notes }}</p></section>
{% endif -%}
<h2>Targets</h2>
<section class="card chips">
{% if targets -%}
{% for target in targets -%}
<span class="chip">{{ target.type }}: {{ target.value }}</span>
{% endfor -%}
{% else -%}
<span class="muted">No selected targets.</span>
{% endif -%}
</section>
<h2>Runs</h2>
<ul class="run-list">
{% if runs -%}
{% for run in runs -%}
<li>
<a class="mono" href="{{ run.href }}">{{ run.label }}</a>
<div class="run-meta">
<span>{{ run.started }}</span>
<span>
{{ run.line_count }} lines
{% if run.text_href -%}
 · <a href="{{ run.text_href }}">full text</a>
{% endif -%}
</span>
<span>{{ run.link_source }} link</span>
{% if run.batch_source -%}<span>{{ run.batch_source }}</span>{% endif -%}
</div>
</li>
{% endfor -%}
{% else -%}
<li class="muted">No selected runs.</li>
{% endif -%}
</ul>
<h2>Findings</h2>
<section class="card">
<table data-sort-table="findings"><thead><tr>
<th><button class="table-sort" type="button" data-sort-key="finding">Finding</button></th>
<th>Targets</th>
<th><button class="table-sort" type="button" data-sort-key="severity">Severity</button></th>
<th><button class="table-sort" type="button" data-sort-key="status">Status</button></th>
<th><button class="table-sort" type="button" data-sort-key="run">Run</button></th>
<th>Evidence</th></tr></thead>
<tbody>
{% if findings -%}
{% for finding in findings -%}
<tr data-finding-row
    data-finding="{{ finding.title }}"
    data-severity="{{ finding.severity }}"
    data-status="{{ finding.status }}"
    data-run="{{ finding.run }}">
<td>
{% if finding.href -%}
<a href="{{ finding.href }}">{{ finding.label }}</a>
{% else -%}
{{ finding.label }}
{% endif -%}
</td>
<td>
{% if finding.targets -%}
<div class="chips">
{% for target in finding.targets -%}
<span class="chip">{{ target }}</span>
{% endfor -%}
</div>
{% else -%}
<span class="muted">No target reference</span>
{% endif -%}
</td>
<td>{{ finding.severity }}</td>
<td>{{ finding.status }}</td>
<td class="mono">{{ finding.run }}</td>
<td class="mono">{{ finding.raw_line }}
{% if finding.labels -%}
<div class="chips">
{% for label in finding.labels -%}
<span class="chip">{{ label }}</span>
{% endfor -%}
</div>
{% endif -%}
{% if finding.note -%}
<blockquote>{{ finding.note }}</blockquote>
{% endif -%}
</td>
</tr>
{% endfor -%}
{% else -%}
<tr><td colspan="6" class="muted">No selected findings.</td></tr>
{% endif -%}
</tbody></table>
</section>
{% if assessment_context -%}
<h2>Assessment Coverage</h2>
<section class="card">
<p><strong>{{ assessment_context.assessment.title }}</strong> · {{ assessment_context.assessment.status }} ·
{{ assessment_context.rollup.covered_checks }} of \
{{ assessment_context.methodology.applicable_denominator }} applicable checks covered</p>
<p>{{ assessment_context.methodology.summary }}</p>
<div class="chips">
<span class="chip">Awaiting review: {{ assessment_context.rollup.checks_awaiting_review }}</span>
<span class="chip">Untested: {{ assessment_context.rollup.untested_checks }}</span>
<span class="chip">Excluded: {{ assessment_context.rollup.excluded_checks }}</span>
<span class="chip">Unavailable evidence: {{ assessment_context.rollup.unavailable_evidence_checks }}</span>
</div>
{% if assessment_context.manual_exclusions -%}
<h3>Manual exclusions</h3>
<table><thead><tr><th>Check</th><th>Target</th><th>State</th><th>Reason</th></tr></thead><tbody>
{% for item in assessment_context.manual_exclusions -%}
<tr><td><span class="mono">{{ item.check_id }}</span></td>
<td>{{ item.target_value }}</td><td>{{ item.state }}</td><td>{{ item.reason }}</td></tr>
{% endfor -%}
</tbody></table>
{% endif -%}
{% if assessment_context.unavailable_evidence_warnings or assessment_context.screenshot_warnings -%}
<h3>Coverage warnings</h3><ul>
{% for item in assessment_context.unavailable_evidence_warnings -%}
<li><span class="mono">{{ item.check_id }}</span>: {{ item.reason }}</li>{% endfor -%}
{% for item in assessment_context.screenshot_warnings -%}
<li><span class="mono">{{ item.artifact_id }}</span>: {{ item.reason }}</li>{% endfor -%}
</ul>
{% endif -%}
{% if assessment_context.fix_first["items"] -%}
<h3>Fix first</h3>
<table><thead><tr><th>Remediation</th><th>Signals</th><th>Observations</th></tr></thead><tbody>
{% for item in assessment_context.fix_first["items"] -%}
<tr><td>{{ item.title }}<br><span class="mono">{{ item.remediation_id }}</span></td>
<td>{% for reason in item.risk.priority_reasons %}{{ reason }}{% if not loop.last %}; {% endif %}{% endfor %}</td>
<td>{{ item.observation_count }} observations · {{ item.evidence_count }} evidence sources</td></tr>
{% endfor -%}
</tbody></table>
{% endif -%}
</section>
{% endif -%}
{% if finding_changes -%}
<h2>Assessment Finding Changes</h2>
<section class="card">
<p><strong>{{ finding_changes.assessment_title }}</strong> · {{ finding_changes.comparison }}</p>
<div class="chips">
{% for metric in finding_changes.rollup -%}
<span class="chip">{{ metric.label }}: {{ metric.count }}</span>
{% endfor -%}
</div>
<p class="muted">Counts are distinct remediation groups, not evidence observations.</p>
<table><thead><tr><th>State</th><th>Remediation</th><th>Current</th><th>Earlier</th><th>Comparison reason</th></tr></thead>
<tbody>
{% for item in finding_changes["items"] -%}
<tr>
<td>{{ item.state }}</td>
<td><strong>{{ item.label }}</strong><br><span class="mono">{{ item.remediation_id }}</span></td>
<td>
{% for finding in item.current_findings -%}
{% if finding.href -%}<a href="{{ finding.href }}">{{ finding.label }}</a>{% else -%}{{ finding.label }}{% endif -%}<br>
{% endfor -%}
{% for evidence_id in item.current_evidence_ids -%}<span class="mono">{{ evidence_id }}</span><br>{% endfor -%}
{% if not item.current_findings and not item.current_evidence_ids -%}<span class="muted">None</span>{% endif -%}
</td>
<td>
{% for finding in item.previous_findings -%}
{% if finding.href -%}<a href="{{ finding.href }}">{{ finding.label }}</a>{% else -%}{{ finding.label }}{% endif -%}<br>
{% endfor -%}
{% for evidence_id in item.previous_evidence_ids -%}<span class="mono">{{ evidence_id }}</span><br>{% endfor -%}
{% if not item.previous_findings and not item.previous_evidence_ids -%}<span class="muted">None</span>{% endif -%}
</td>
<td>
{% if item.reasons -%}{{ item.reasons | join('; ') }}
{% else -%}<span class="muted">No exception recorded</span>
{% endif -%}
</td>
</tr>
{% endfor -%}
</tbody></table>
</section>
{% endif -%}
<h2>Artifacts</h2>
<section class="card">
<table><thead><tr><th>Artifact</th><th>Workspace path</th><th>Bytes</th><th>Run</th></tr></thead>
<tbody>
{% if artifacts -%}
{% for artifact in artifacts -%}
<tr>
<td>
{% if artifact.href -%}
<a href="{{ artifact.href }}">{{ artifact.name }}</a>
{% else -%}
{{ artifact.name }}
{% endif -%}
</td>
<td>{{ artifact.workspace_path }}</td>
<td>{{ artifact.byte_size }}</td>
<td class="mono">{{ artifact.run }}</td>
</tr>
{% endfor -%}
{% else -%}
<tr><td colspan="4" class="muted">No selected artifacts.</td></tr>
{% endif -%}
</tbody></table>
</section>
<h2>Package Exports</h2>
<section class="card"><ul>
{% for export in export_links -%}
<li><a href="{{ export.href }}">{{ export.label }}</a></li>
{% endfor -%}
</ul></section>
{% if skipped_items -%}
<h2>Skipped Items</h2>
<section class="card"><ul>
{% for item in skipped_items -%}
<li>
<span class="chip">{{ item.kind }}</span>
<span class="mono">{{ item.label }}</span>
<span class="muted">{{ item.reason }}</span>
</li>
{% endfor -%}
</ul></section>
{% endif -%}
<p class="footer">Generated by darklab shell evidence packages. Redaction mode is recorded in manifest.json.</p>
</main>
""")


def _package_zip_artifact_path(workspace_path, used_paths, *, root="artifacts"):
    parts = [
        part for part in PurePosixPath(str(workspace_path or "").replace("\\", "/")).parts
        if part not in {"", ".", ".."}
    ]
    relative = "/".join(parts) or "artifact"
    root = str(root or "artifacts").strip("/.") or "artifacts"
    candidate = f"{root}/{relative}"
    if candidate not in used_paths:
        used_paths.add(candidate)
        return candidate
    stem = PurePosixPath(relative).stem or "artifact"
    suffix = PurePosixPath(relative).suffix
    parent = str(PurePosixPath(relative).parent)
    prefix = "" if parent in {"", "."} else f"{parent}/"
    for index in range(2, 1000):
        candidate = f"{root}/{prefix}{stem}-{index}{suffix}"
        if candidate not in used_paths:
            used_paths.add(candidate)
            return candidate
    raise ProjectWorkspaceError("could not allocate artifact package path")


def _package_short_id(value):
    text = str(value or "")
    return text[:12] if len(text) > 12 else text


def _package_batch_source(run) -> str:
    provenance = run.get("assessment_batch") if isinstance(run, dict) else None
    if not isinstance(provenance, dict) or not provenance.get("batch_id"):
        return ""
    item = value if isinstance(value := provenance.get("item"), dict) else {}
    item_number = int(item.get("item_index") or 0) + 1
    check_count = int(item.get("check_count") or 0)
    mapped = f" · {check_count} mapped check{'s' if check_count != 1 else ''}" if check_count else ""
    return f"Assessment batch {provenance['batch_id']} · item {item_number}{mapped}"


def _package_int(value, default=0):
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _package_markdown_text(value):
    text = str(value or "").replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\n", " ").strip()
    return re.sub(r"([\\`*_{}\[\]<>()#+!|])", r"\\\1", text)


def _package_markdown_code(value):
    text = str(value or "").replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\n", " ").strip()
    if not text:
        return "``"
    text = text.replace("|", "\\|")
    longest_tick = max((len(match.group(0)) for match in re.finditer(r"`+", text)), default=0)
    fence = "`" * (longest_tick + 1)
    return f"{fence}{text}{fence}" if longest_tick == 0 else f"{fence} {text} {fence}"


def _package_markdown_link(label, href):
    safe_label = _package_markdown_text(label) or "link"
    safe_href = str(href or "").replace(")", "%29").replace(" ", "%20")
    return f"[{safe_label}]({safe_href})" if safe_href else safe_label


def _package_target_reference_label(reference):
    if not isinstance(reference, dict):
        return ""
    target_type = str(reference.get("type") or "target")
    value = str(reference.get("value") or reference.get("target_id") or "")
    source = str(reference.get("relationship_source") or "")
    source_run = str(reference.get("source_run_id") or "")
    label = f"{target_type}: {value}" if value else target_type
    details = [item for item in (source, f"run {_package_short_id(source_run)}" if source_run else "") if item]
    return f"{label} ({', '.join(details)})" if details else label


def _package_finding_target_reference_labels(finding):
    references = finding.get("target_references") if isinstance(finding, dict) else None
    labels = [
        _package_target_reference_label(reference)
        for reference in references
        if isinstance(reference, dict)
    ] if isinstance(references, list) else []
    labels = [label for label in labels if label]
    if labels:
        return labels
    return _package_finding_target_ids(finding)


def _package_output_entry(item) -> dict[str, object]:
    if isinstance(item, dict) and isinstance(item.get("text"), str):
        return to_legacy_entry(
            line_event_from_legacy(
                item["text"],
                item.get("cls", ""),
                ts_clock=item.get("tsC", ""),
                ts_elapsed=item.get("tsE", ""),
                signals=item.get("signals") if isinstance(item.get("signals"), list) else None,
                line_index=item.get("line_index"),
                command_root=item.get("command_root", ""),
                target=item.get("target", ""),
                entities=item.get("entities") if isinstance(item.get("entities"), list) else None,
                source_detail=item.get("source_detail") if isinstance(item.get("source_detail"), dict) else None,
            )
        )
    return to_legacy_entry(line_event_from_legacy(str(item or "")))


def _package_preview_output_entries(run) -> list[dict[str, object]]:
    raw = run.get("output_preview")
    if raw is None:
        raw = run.get("output")
    if not raw:
        return []
    try:
        loaded = json.loads(raw)
    except (TypeError, ValueError):
        return [to_legacy_entry(line_event_from_legacy(line)) for line in str(raw).splitlines()]
    if not isinstance(loaded, list):
        return [to_legacy_entry(line_event_from_legacy(str(loaded)))]
    return [_package_output_entry(item) for item in loaded]


def _package_run_rows(conn, session_id, run_ids, *, team_id=""):
    ids = [str(run_id) for run_id in run_ids if run_id]
    if not ids:
        return []
    placeholders = ",".join("?" for _ in ids)
    owner_sql, owner_params = shared_owner_where(session_id, team_id=team_id, table_alias="r")
    rows = conn.execute(
        "SELECT r.*, art.rel_path "  # nosec
        "FROM runs r LEFT JOIN run_output_artifacts art ON art.run_id = r.id "
        "WHERE " + owner_sql + f" AND r.id IN ({placeholders})",  # nosec
        [*owner_params, *ids],
    ).fetchall()
    by_id = {str(row["id"]): dict(row) for row in rows}
    provenance_by_run = assessment_batch_provenance_by_run(
        conn,
        ids,
        session_id=session_id,
        team_id=team_id,
    )
    for run_id, run in by_id.items():
        provenance = provenance_by_run.get(run_id)
        if provenance:
            apply_assessment_batch_provenance(run, provenance)
    return [by_id[run_id] for run_id in ids if run_id in by_id]


def _package_run_output_entries(run, *, cfg=None, include_companion=False):
    if run.get("full_output_available") and run.get("rel_path"):
        try:
            entries = load_full_output_entries(str(run["rel_path"]))
        except (OSError, gzip.BadGzipFile, EOFError, ValueError) as exc:
            log.warning("PACKAGE_FULL_OUTPUT_PREVIEW_FALLBACK", extra={
                "run_id": str(run.get("id") or ""),
                "rel_path": str(run.get("rel_path") or ""),
                "error": str(exc),
            })
            entries = _package_preview_output_entries(run)
        if run.get("full_output_truncated"):
            entries.append(to_legacy_entry(line_event_from_legacy(
                "[full output truncated by the server-side capture limit]",
                kind=LineKind.warn,
            )))
    else:
        entries = _package_preview_output_entries(run)
        if run.get("preview_truncated"):
            entries.append(to_legacy_entry(line_event_from_legacy(
                "[preview truncated; full output was not available for this package export]",
                kind=LineKind.warn,
            )))

    max_lines = _cfg_int("max_output_lines", 5000, cfg=cfg) or 5000
    if len(entries) > max_lines:
        hidden = len(entries) - max_lines
        log.warning("PACKAGE_TRANSCRIPT_CAPPED", extra={
            "run_id": str(run.get("id") or ""),
            "max_lines": max_lines,
            "hidden_lines": hidden,
            "include_companion": include_companion,
        })
        companion_entries = list(entries)
        capped_entries: list[dict[str, object]] = list(entries[:max_lines])
        cap_notice = to_legacy_entry(line_event_from_legacy(
            f"[package transcript capped at {max_lines} lines; {hidden} additional lines omitted]",
            kind=LineKind.warn,
        ))
        capped_entries.append(cap_notice)
        if include_companion:
            return capped_entries, companion_entries, cap_notice
        return capped_entries
    if include_companion:
        return entries, [], None
    return entries


def _package_run_text_bytes(entries, redaction_rules=None):
    entries = line_entries_from_events(redact_line_entries(entries, redaction_rules)) if redaction_rules else entries
    lines = []
    for entry in entries:
        if isinstance(entry, dict):
            lines.append(str(entry.get("text") or ""))
        else:
            lines.append(str(entry or ""))
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def _package_css():
    return (
        "/* darklab shell evidence package CSS snapshot: package_format_version=2 */\n"
        + _font_face_css(embed=True)
        + "\n"
        + """
:root {
  color-scheme: dark;
  --bg: #0f1215;
  --panel: #171c20;
  --panel-2: #20272d;
  --text: #e6edf3;
  --muted: #9da9b5;
  --accent: #54d18a;
  --border: #303a43;
  --danger: #ff7b72;
  --warn: #f2c94c;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.5;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.page { width: min(1180px, calc(100vw - 32px)); margin: 0 auto; padding: 32px 0 48px; }
.topline { color: var(--muted); font-size: 0.82rem; text-transform: uppercase; letter-spacing: 0.08em; }
h1, h2, h3 { margin: 0; line-height: 1.2; }
h1 { margin-top: 8px; font-size: clamp(2rem, 5vw, 3.7rem); }
h2 { margin: 32px 0 12px; font-size: 1.15rem; }
.subtitle { max-width: 780px; margin: 12px 0 0; color: var(--muted); }
.grid { display: grid; gap: 12px; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); margin-top: 24px; }
.metric, .card, .transcript {
  border: 1px solid var(--border);
  background: var(--panel);
  border-radius: 8px;
}
.metric { padding: 14px; }
.metric strong { display: block; font-size: 1.6rem; }
.metric span { color: var(--muted); font-size: 0.88rem; }
.card { padding: 16px; margin-top: 12px; }
.chips { display: flex; flex-wrap: wrap; gap: 8px; }
.chip {
  display: inline-flex;
  align-items: center;
  max-width: 100%;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--panel-2);
  color: var(--text);
  font-size: 0.82rem;
  padding: 4px 9px;
}
table { width: 100%; border-collapse: collapse; overflow-wrap: anywhere; }
th, td { padding: 10px 8px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: top; }
th { color: var(--muted); font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.06em; }
button.table-sort {
  appearance: none;
  border: 0;
  padding: 0;
  background: transparent;
  color: inherit;
  font: inherit;
  letter-spacing: inherit;
  text-transform: inherit;
  cursor: pointer;
}
button.table-sort::after { content: " ↕"; color: var(--muted); }
button.table-sort[aria-sort="ascending"]::after { content: " ↑"; color: var(--accent); }
button.table-sort[aria-sort="descending"]::after { content: " ↓"; color: var(--accent); }
blockquote { margin: 8px 0 0; padding-left: 10px; border-left: 2px solid var(--border); color: var(--muted); }
.muted { color: var(--muted); }
.warn { color: var(--warn); }
.fail { color: var(--danger); }
.mono, .transcript {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
}
.run-list { list-style: none; padding: 0; margin: 0; display: grid; gap: 10px; }
.run-list li { border: 1px solid var(--border); border-radius: 8px; padding: 12px; background: var(--panel); }
.run-meta { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; color: var(--muted); font-size: 0.84rem; }
.transcript { padding: 16px; overflow: auto; white-space: pre-wrap; }
.line { min-height: 1.35em; }
.prompt-echo { color: var(--accent); }
.line.warn { color: var(--warn); }
.line:target { background: color-mix(in srgb, var(--accent) 18%, transparent); outline: 1px solid var(--accent); }
.footer { margin-top: 36px; color: var(--muted); font-size: 0.84rem; }
@media (max-width: 720px) {
  .page { width: min(100vw - 20px, 1180px); padding-top: 20px; }
  th:nth-child(4), td:nth-child(4) { display: none; }
}
""".strip()
    )


def _package_page(title, body, script="", *, css_href="assets/package.css"):
    return _PACKAGE_PAGE_TEMPLATE.render(
        title=title or "",
        css_href=css_href or "",
        inline_css=_package_css() if not css_href else "",
        body=body or "",
        script=script or "",
    )


def _render_package_run_html(
    run,
    entries,
    manifest,
    generated_at,
    *,
    transcript_text_path="",
    redaction_rules=None,
):
    entries = line_entries_from_events(redact_line_entries(entries, redaction_rules)) if redaction_rules else entries
    run = _redact_package_run(run, redaction_rules)
    command = str(run.get("command") or "")
    started = str(run.get("started") or "")
    finished = str(run.get("finished") or "")
    duration = _format_duration(started, finished)
    output_line_count = run.get("output_line_count")
    line_count = output_line_count if isinstance(output_line_count, int) else len(entries)
    if isinstance(output_line_count, str) and output_line_count.isdecimal():
        line_count = int(output_line_count)
    meta = {
        "exit_code": run.get("exit_code"),
        "duration": duration,
        "lines": f"{line_count:,} lines",
        "artifact_count": run.get("artifact_count") or 0,
        "finding_count": run.get("finding_count") or 0,
        "label_count": run.get("label_count") or 0,
        "note_count": run.get("note_count") or 0,
    }
    permalink_model = _permalink_context(
        title=command or str(run.get("id") or "Run transcript"),
        label=command,
        created=started or generated_at,
        content_lines=entries,
        json_url="../manifest.json",
        extra_actions=[],
        meta=meta,
    )["page_model"]
    normalized = permalink_model["transcript"]["lines"]
    rendered_lines = []
    for index, entry in enumerate(normalized, start=1):
        text = entry.get("text", "") if isinstance(entry, dict) else entry
        cls = str(entry.get("cls", "") if isinstance(entry, dict) else "")
        line_index = entry.get("line_index") if isinstance(entry, dict) else None
        line_id = f"L{line_index + 1}" if isinstance(line_index, int) else f"line-{index}"
        rendered_lines.append({
            "id": line_id,
            "class_name": f"line {cls}".strip(),
            "text": text,
        })

    header = permalink_model.get("header", {})
    raw_metric_items = header.get("runMetaItems") if isinstance(header, dict) else []
    metric_items = raw_metric_items if isinstance(raw_metric_items, list) else []
    rendered_metric_items = [
        {"kind": item.get("kind") or "item", "text": item.get("text") or ""}
        for item in metric_items
        if isinstance(item, dict)
    ]
    if not rendered_metric_items:
        rendered_metric_items = [
            {"kind": label, "text": value}
            for label, value in [
                ("Started", started or "unknown"),
                ("Finished", finished or "unknown"),
                ("Duration", duration or "unknown"),
                ("Lines", line_count),
            ]
        ]
    batch_source = _package_batch_source(run)
    if batch_source:
        rendered_metric_items.append({"kind": "Source", "text": batch_source})
    project_name = (
        manifest.get("project", {}).get("name", "Project")
        if isinstance(manifest.get("project"), dict)
        else "Project"
    )
    body = _PACKAGE_RUN_TEMPLATE.render(
        project_name=project_name,
        title=command or run.get("id") or "Run transcript",
        run_id=run.get("id") or "",
        generated_at=generated_at,
        metric_items=rendered_metric_items,
        transcript_text_path=transcript_text_path or "",
        lines=rendered_lines,
    )
    return _package_page(command or "Run transcript", body, css_href="../assets/package.css")


def _finding_run_anchor(finding):
    run_id = str(finding.get("run_id") or "")
    line_number = finding.get("line_number")
    if isinstance(line_number, int):
        return f"runs/{run_id}.html#L{line_number + 1}"
    return f"runs/{run_id}.html"


def _package_finding_metadata_markdown(finding):
    labels = finding.get("labels") if isinstance(finding.get("labels"), list) else []
    note = finding.get("note") if isinstance(finding.get("note"), dict) else None
    triage = finding.get("triage") if isinstance(finding.get("triage"), dict) else None
    parts = []
    label_values = [
        _package_markdown_code(label.get("label") or "")
        for label in labels
        if isinstance(label, dict) and label.get("label")
    ]
    if label_values:
        parts.append("Labels: " + ", ".join(label_values))
    if triage:
        verification_status = str(triage.get("verification_status") or "not_started").strip()
        remediation = str(triage.get("remediation") or "").strip()
        verification_steps = str(triage.get("verification_steps") or "").strip()
        verification_notes = str(triage.get("verification_notes") or "").strip()
        if verification_status and verification_status != "not_started":
            parts.append("Verification: " + _package_markdown_code(verification_status))
        if remediation:
            parts.append("Remediation: " + _package_markdown_text(remediation))
        if verification_steps:
            parts.append("Verification steps: " + _package_markdown_text(verification_steps))
        if verification_notes:
            parts.append("Verification notes: " + _package_markdown_text(verification_notes))
    if note and note.get("body"):
        parts.append("Note: " + _package_markdown_text(note.get("body") or ""))
    return "<br>" + "<br>".join(parts) if parts else ""


def _package_index_sort_script():
    return """
<script>
(() => {
  const table = document.querySelector("[data-sort-table='findings']");
  if (!table) return;
  const body = table.querySelector("tbody");
  if (!body) return;
  const buttons = table.querySelectorAll("[data-sort-key]");
  buttons.forEach((button) => {
    button.addEventListener("click", () => {
      const key = button.dataset.sortKey;
      const current = button.getAttribute("aria-sort");
      const direction = current === "ascending" ? "descending" : "ascending";
      buttons.forEach((item) => item.removeAttribute("aria-sort"));
      button.setAttribute("aria-sort", direction);
      const rows = Array.from(body.querySelectorAll("tr[data-finding-row]"));
      rows.sort((left, right) => {
        const leftValue = left.dataset[key] || "";
        const rightValue = right.dataset[key] || "";
        const result = leftValue.localeCompare(rightValue, undefined, { numeric: true, sensitivity: "base" });
        return direction === "ascending" ? result : -result;
      });
      rows.forEach((row) => body.appendChild(row));
    });
  });
})();
</script>
""".strip()


def _package_finding_change_link(finding, manifest_findings, run_pages):
    finding_id = str(finding.get("id") or "") if isinstance(finding, dict) else ""
    source = manifest_findings.get(finding_id, {})
    run_id = str(source.get("run_id") or "") if isinstance(source, dict) else ""
    return {
        "label": str(finding.get("title") or finding_id or "Finding source unavailable"),
        "href": _finding_run_anchor(source) if run_id in run_pages else "",
    }


def _package_finding_changes(manifest, run_pages):
    source = manifest.get("assessment_finding_changes")
    if not isinstance(source, dict):
        return None
    raw_assessment = source.get("assessment")
    raw_comparison = source.get("comparison")
    raw_rollup = source.get("rollup")
    assessment = raw_assessment if isinstance(raw_assessment, dict) else {}
    comparison = raw_comparison if isinstance(raw_comparison, dict) else {}
    rollup = raw_rollup if isinstance(raw_rollup, dict) else {}
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    manifest_findings = {
        str(finding.get("id") or ""): finding
        for finding in findings
        if isinstance(finding, dict) and finding.get("id")
    }
    items = []
    for item in source.get("items", []):
        if not isinstance(item, dict):
            continue
        items.append({
            "remediation_id": str(item.get("remediation_id") or ""),
            "state": str(item.get("state") or "incomparable").replace("_", " "),
            "label": str(item.get("vulnerability_id") or item.get("rule_identity") or "Saved remediation"),
            "reasons": [str(value) for value in item.get("reasons", []) if str(value or "")],
            "current_findings": [
                _package_finding_change_link(finding, manifest_findings, run_pages)
                for finding in item.get("current_findings", [])
                if isinstance(finding, dict)
            ],
            "previous_findings": [
                _package_finding_change_link(finding, manifest_findings, run_pages)
                for finding in item.get("previous_findings", [])
                if isinstance(finding, dict)
            ],
            "current_evidence_ids": [str(value) for value in item.get("current_evidence_ids", [])],
            "previous_evidence_ids": [str(value) for value in item.get("previous_evidence_ids", [])],
        })
    return {
        "assessment_title": str(assessment.get("title") or assessment.get("id") or "Assessment cycle"),
        "comparison": (
            f"{_package_int(comparison.get('comparable_checks'))} of "
            f"{_package_int(comparison.get('total_checks'))} checks comparable"
        ),
        "rollup": [
            {"label": label, "count": _package_int(rollup.get(key))}
            for key, label in (
                ("regressed", "Regressed"),
                ("new", "New"),
                ("persistent", "Persistent"),
                ("not_observed", "Not observed"),
                ("incomparable", "Incomparable"),
            )
        ],
        "items": items,
    }


def _append_package_finding_changes_markdown(lines, manifest, run_pages):
    changes = _package_finding_changes(manifest, run_pages)
    if not changes:
        return
    lines.extend([
        "",
        "## Assessment Finding Changes",
        "",
        f"- Cycle: {_package_markdown_text(changes['assessment_title'])}",
        f"- Comparison: {_package_markdown_text(changes['comparison'])}",
        "- Counts are distinct remediation groups, not evidence observations.",
        "",
        "| State | Count |",
        "| --- | ---: |",
    ])
    for metric in changes["rollup"]:
        lines.append(f"| {metric['label']} | {metric['count']} |")
    for item in changes["items"]:
        lines.extend([
            "",
            f"### {_package_markdown_text(item['label'])}",
            "",
            f"- State: {_package_markdown_text(item['state'])}",
            f"- Remediation: {_package_markdown_code(item['remediation_id'])}",
        ])
        for side, label in (("current", "Current"), ("previous", "Earlier")):
            references = [
                _package_markdown_link(finding["label"], finding["href"])
                for finding in item[f"{side}_findings"]
            ]
            references.extend(
                _package_markdown_code(value)
                for value in item[f"{side}_evidence_ids"]
            )
            lines.append(f"- {label}: {', '.join(references) if references else 'None'}")
        reasons = "; ".join(item["reasons"]) or "No exception recorded"
        lines.append(f"- Comparison reason: {_package_markdown_text(reasons)}")


def _append_package_assessment_context_markdown(lines, manifest):
    context = manifest.get("assessment_context")
    if not isinstance(context, dict):
        return
    raw_assessment = context.get("assessment")
    assessment = raw_assessment if isinstance(raw_assessment, dict) else {}
    raw_rollup = context.get("rollup")
    rollup = raw_rollup if isinstance(raw_rollup, dict) else {}
    raw_methodology = context.get("methodology")
    methodology = raw_methodology if isinstance(raw_methodology, dict) else {}
    lines.extend([
        "",
        "## Assessment Coverage",
        "",
        f"- Cycle: {_package_markdown_text(assessment.get('title') or assessment.get('id'))}",
        f"- Cycle ID: {_package_markdown_code(assessment.get('id'))}",
        f"- Status: {_package_markdown_text(assessment.get('status'))}",
        f"- Profile: {_package_markdown_code(assessment.get('profile_key'))} "
        f"{_package_markdown_text(assessment.get('profile_version'))}",
        f"- Applicable denominator: {_package_int(methodology.get('applicable_denominator'))}",
        f"- Covered: {_package_int(rollup.get('covered_checks'))}",
        f"- Awaiting review: {_package_int(rollup.get('checks_awaiting_review'))}",
        f"- Untested: {_package_int(rollup.get('untested_checks'))}",
        f"- Excluded: {_package_int(rollup.get('excluded_checks'))}",
        f"- Unavailable evidence: {_package_int(rollup.get('unavailable_evidence_checks'))}",
        "",
        _package_markdown_text(methodology.get("summary")),
    ])
    exclusions = context.get("manual_exclusions")
    if isinstance(exclusions, list) and exclusions:
        lines.extend(("", "### Manual exclusions", "", "| Check | Target | State | Reason |", "| --- | --- | --- | --- |"))
        for item in exclusions:
            if not isinstance(item, dict):
                continue
            lines.append(
                f"| {_package_markdown_code(item.get('check_id'))} "
                f"| {_package_markdown_text(item.get('target_value'))} "
                f"| {_package_markdown_text(item.get('state'))} "
                f"| {_package_markdown_text(item.get('reason'))} |"
            )
    warnings = [
        *[item for item in context.get("unavailable_evidence_warnings", []) if isinstance(item, dict)],
        *[item for item in context.get("screenshot_warnings", []) if isinstance(item, dict)],
    ]
    if warnings:
        lines.extend(("", "### Coverage warnings", ""))
        for item in warnings:
            lines.append(
                f"- {_package_markdown_code(item.get('check_id') or item.get('artifact_id'))}: "
                f"{_package_markdown_text(item.get('reason'))}"
            )
    raw_fix_first = context.get("fix_first")
    fix_first = raw_fix_first if isinstance(raw_fix_first, dict) else {}
    raw_items = fix_first.get("items")
    items = raw_items if isinstance(raw_items, list) else []
    if items:
        lines.extend(("", "### Fix first", ""))
        for item in items:
            if not isinstance(item, dict):
                continue
            raw_risk = item.get("risk")
            risk = raw_risk if isinstance(raw_risk, dict) else {}
            raw_reasons = risk.get("priority_reasons")
            reasons = raw_reasons if isinstance(raw_reasons, list) else []
            signal_text = "; ".join(str(reason) for reason in reasons) or "No stored CVE-risk signals"
            lines.extend([
                f"#### {_package_markdown_text(item.get('title') or item.get('remediation_id'))}",
                "",
                f"- Remediation: {_package_markdown_code(item.get('remediation_id'))}",
                f"- Signals: {_package_markdown_text(signal_text)}",
                f"- Evidence: {_package_int(item.get('observation_count'))} observations, "
                f"{_package_int(item.get('evidence_count'))} evidence sources",
                "",
            ])


def _render_package_index_html(
    package,
    manifest,
    generated_at,
    run_pages,
    run_text_paths,
    artifact_paths,
    skipped_items,
):
    project = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}
    counts = manifest.get("counts") if isinstance(manifest.get("counts"), dict) else {}
    targets = manifest.get("targets") if isinstance(manifest.get("targets"), list) else []
    runs = manifest.get("runs") if isinstance(manifest.get("runs"), list) else []
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    artifacts = manifest.get("artifacts") if isinstance(manifest.get("artifacts"), list) else []

    project_notes = _entity_note_body(project)
    metric_items = [
        {"label": label, "count": counts.get(key, 0)}
        for key, label in (
            ("runs", "Runs"),
            ("findings", "Findings"),
            ("artifacts", "Artifacts"),
            ("targets", "Targets"),
        )
    ]
    target_items = [
        {"type": target.get("type", "target"), "value": target.get("value", "")}
        for target in targets
        if isinstance(target, dict)
    ]
    run_items = []
    for run in runs:
        if not isinstance(run, dict):
            continue
        run_id = str(run.get("id") or "")
        run_items.append({
            "href": run_pages.get(run_id, ""),
            "label": run.get("command") or run_id,
            "started": run.get("started") or "unknown start",
            "line_count": run.get("output_line_count") or 0,
            "text_href": run_text_paths.get(run_id, ""),
            "link_source": run.get("link_source") or "manual",
            "batch_source": _package_batch_source(run),
        })

    finding_items = []
    for finding in findings:
        if not isinstance(finding, dict):
            continue
        finding_run_id = str(finding.get("run_id") or "")
        finding_href = _finding_run_anchor(finding) if finding_run_id in run_pages else ""
        raw_labels = finding.get("labels")
        labels = raw_labels if isinstance(raw_labels, list) else []
        note = finding.get("note") if isinstance(finding.get("note"), dict) else None
        finding_items.append({
            "href": finding_href,
            "label": finding.get("title") or finding.get("raw_line") or "",
            "title": finding.get("title") or finding.get("raw_line") or "",
            "targets": _package_finding_target_reference_labels(finding),
            "severity": finding.get("severity") or "info",
            "status": finding.get("review_state") or "new",
            "run": _package_short_id(finding.get("run_id")),
            "raw_line": finding.get("raw_line") or "",
            "labels": [
                label.get("label") or ""
                for label in labels
                if isinstance(label, dict) and label.get("label")
            ],
            "note": note.get("body") if note and note.get("body") else "",
        })

    finding_changes = _package_finding_changes(manifest, run_pages)
    assessment_context = manifest.get("assessment_context")
    if not isinstance(assessment_context, dict):
        assessment_context = None

    artifact_items = []
    for artifact in artifacts:
        if not isinstance(artifact, dict):
            continue
        artifact_id = str(artifact.get("id") or "")
        name = artifact.get("display_name") or artifact.get("workspace_path") or artifact_id
        artifact_items.append({
            "href": artifact_paths.get(artifact_id, ""),
            "name": name,
            "workspace_path": artifact.get("workspace_path") or "",
            "byte_size": artifact.get("byte_size") or 0,
            "run": _package_short_id(artifact.get("run_id")),
        })

    export_links = [
        {"label": "Manifest JSON", "href": "manifest.json"},
        {"label": "README Markdown", "href": "README.md"},
        {"label": "Findings JSON", "href": "findings/findings.json"},
        {"label": "Findings Markdown", "href": "findings/findings.md"},
        {"label": "Targets JSON", "href": "targets/targets.json"},
        {"label": "Targets Markdown", "href": "targets/targets.md"},
        {"label": "Labels JSON", "href": "metadata/labels.json"},
        {"label": "Entity Notes JSON", "href": "notes/entity-notes.json"},
        {"label": "Entity Notes Markdown", "href": "notes/entity-notes.md"},
    ]
    if project_notes:
        export_links.append({"label": "Project Notes Markdown", "href": "notes/project.md"})
    if skipped_items:
        export_links.append({"label": "Skipped items JSON", "href": "skipped-items.json"})

    skipped_item_rows = [
        {
            "kind": item.get("kind") or "item",
            "label": item.get("label") or item.get("workspace_path") or item.get("id"),
            "reason": item.get("reason") or "skipped",
        }
        for item in skipped_items
        if isinstance(item, dict)
    ]

    body = _PACKAGE_INDEX_TEMPLATE.render(
        package_name=package.get("name") or "Evidence package",
        project_name=project.get("name") or "Project",
        generated_at=generated_at,
        metrics=metric_items,
        project_notes=project_notes,
        targets=target_items,
        runs=run_items,
        findings=finding_items,
        assessment_context=assessment_context,
        finding_changes=finding_changes,
        artifacts=artifact_items,
        export_links=export_links,
        skipped_items=skipped_item_rows,
    )
    return _package_page(
        str(package.get("name") or "Evidence package"),
        body,
        _package_index_sort_script(),
    )


def _render_package_readme(
    package,
    manifest,
    generated_at,
    run_pages,
    run_text_paths,
    artifact_paths,
    skipped_items,
):
    project = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}
    counts = manifest.get("counts") if isinstance(manifest.get("counts"), dict) else {}
    targets = manifest.get("targets") if isinstance(manifest.get("targets"), list) else []
    runs = manifest.get("runs") if isinstance(manifest.get("runs"), list) else []
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    artifacts = manifest.get("artifacts") if isinstance(manifest.get("artifacts"), list) else []
    provenance_value = manifest.get("provenance")
    provenance = provenance_value if isinstance(provenance_value, dict) else {}
    audit_value = provenance.get("audit")
    audit = audit_value if isinstance(audit_value, dict) else {}
    audit_correlation_id = str(audit.get("correlation_id") or "").strip()
    lines = [
        f"# {_package_markdown_text(package.get('name') or 'Evidence package')}",
        "",
        f"- Project: {_package_markdown_text(project.get('name') or 'Project')}",
        f"- Generated: {_package_markdown_text(generated_at)}",
        f"- Preset: {_package_markdown_text(manifest.get('preset') or 'custom')}",
        f"- Redaction mode: {_package_markdown_text(manifest.get('redaction_mode') or 'raw')}",
    ]
    if audit_correlation_id:
        lines.append(f"- Audit correlation: {_package_markdown_code(audit_correlation_id)}")
    lines.extend([
        "",
        "## Counts",
        "",
        "| Type | Count |",
        "| --- | ---: |",
    ])
    for key, label in (("runs", "Runs"), ("findings", "Findings"), ("artifacts", "Artifacts"), ("targets", "Targets")):
        lines.append(f"| {label} | {_package_int(counts.get(key))} |")
    project_notes = _entity_note_body(project)
    if project_notes:
        lines.extend([
            "",
            "## Project Notes",
            "",
            _package_markdown_text(project_notes),
        ])
    lines.extend(["", "## Targets", ""])
    if targets:
        for target in targets:
            if isinstance(target, dict):
                lines.append(
                    f"- {_package_markdown_code(target.get('type') or 'target')} "
                    f"{_package_markdown_text(target.get('value') or '')}"
                )
    else:
        lines.append("- No selected targets.")
    lines.extend(["", "## Runs", ""])
    if runs:
        for run in runs:
            if not isinstance(run, dict):
                continue
            run_id = str(run.get("id") or "")
            label = run.get("command") or run_id
            lines.append(f"- {_package_markdown_link(label, run_pages.get(run_id, ''))}")
            lines.append(f"  - Started: {_package_markdown_text(run.get('started') or 'unknown')}")
            lines.append(f"  - Lines: {_package_int(run.get('output_line_count'))}")
            batch_source = _package_batch_source(run)
            if batch_source:
                lines.append(f"  - Source: {_package_markdown_text(batch_source)}")
            if run_text_paths.get(run_id):
                lines.append(f"  - Full text: {_package_markdown_link('transcript text', run_text_paths[run_id])}")
    else:
        lines.append("- No selected runs.")
    lines.extend(["", "## Findings", ""])
    if findings:
        lines.extend([
            "| Finding | Targets | Severity | Status | Run | Evidence |",
            "| --- | --- | --- | --- | --- | --- |",
        ])
        for finding in findings:
            if not isinstance(finding, dict):
                continue
            run_id = str(finding.get("run_id") or "")
            href = _finding_run_anchor(finding) if run_id in run_pages else ""
            finding_label = finding.get("title") or finding.get("raw_line") or finding.get("id")
            lines.append(
                f"| {_package_markdown_link(finding_label, href)} "
                f"| {_package_markdown_text('; '.join(_package_finding_target_reference_labels(finding)))} "
                f"| {_package_markdown_text(finding.get('severity') or 'info')} "
                f"| {_package_markdown_text(finding.get('review_state') or 'new')} "
                f"| {_package_markdown_code(_package_short_id(run_id))} "
                f"| {_package_markdown_code(finding.get('raw_line') or '')}"
                f"{_package_finding_metadata_markdown(finding)} |"
            )
    else:
        lines.append("- No selected findings.")
    _append_package_assessment_context_markdown(lines, manifest)
    _append_package_finding_changes_markdown(lines, manifest, run_pages)
    lines.extend(["", "## Artifacts", ""])
    if artifacts:
        lines.extend(["| Artifact | Workspace Path | Bytes | Run |", "| --- | --- | ---: | --- |"])
        for artifact in artifacts:
            if not isinstance(artifact, dict):
                continue
            artifact_id = str(artifact.get("id") or "")
            name = artifact.get("display_name") or artifact.get("workspace_path") or artifact_id
            lines.append(
                f"| {_package_markdown_link(name, artifact_paths.get(artifact_id, ''))} "
                f"| {_package_markdown_code(artifact.get('workspace_path') or '')} "
                f"| {_package_int(artifact.get('byte_size'))} "
                f"| {_package_markdown_code(_package_short_id(artifact.get('run_id')))} |"
            )
    else:
        lines.append("- No selected artifacts.")
    lines.extend(["", "## Skipped Items", ""])
    if skipped_items:
        for item in skipped_items:
            label = item.get("label") or item.get("workspace_path") or item.get("id") or "item"
            lines.append(
                f"- {_package_markdown_code(item.get('kind') or 'item')} "
                f"{_package_markdown_text(label)}: {_package_markdown_text(item.get('reason') or 'skipped')}"
            )
    else:
        lines.append("- No skipped items.")
    lines.extend([
        "",
        "## Package Exports",
        "",
        f"- {_package_markdown_link('Manifest JSON', 'manifest.json')}",
        f"- {_package_markdown_link('Findings JSON', 'findings/findings.json')}",
        f"- {_package_markdown_link('Findings Markdown', 'findings/findings.md')}",
        f"- {_package_markdown_link('Targets JSON', 'targets/targets.json')}",
        f"- {_package_markdown_link('Targets Markdown', 'targets/targets.md')}",
        f"- {_package_markdown_link('Labels JSON', 'metadata/labels.json')}",
        f"- {_package_markdown_link('Entity Notes JSON', 'notes/entity-notes.json')}",
        f"- {_package_markdown_link('Entity Notes Markdown', 'notes/entity-notes.md')}",
    ])
    if project_notes:
        lines.append(f"- {_package_markdown_link('Project Notes Markdown', 'notes/project.md')}")
    if skipped_items:
        lines.append(f"- {_package_markdown_link('Skipped items JSON', 'skipped-items.json')}")
    lines.extend([
        "",
        "## Notes",
        "",
        "Generated by darklab shell evidence packages. Redaction mode is recorded in manifest.json.",
        "",
    ])
    return "\n".join(lines)


def _package_collection_json_bytes(collection_name, items, generated_at, *, extra=None):
    exported = items if isinstance(items, list) else []
    payload = {
        "format": 1,
        "generated_at": generated_at,
        "count": len(exported),
        collection_name: exported,
    }
    if extra:
        payload.update(extra)
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _package_collection_markdown_bytes(title, generated_at, body_lines, *, empty_message):
    lines = [f"# {_package_markdown_text(title)}", ""]
    if generated_at is not None:
        lines.extend([f"Generated: {_package_markdown_text(generated_at)}", ""])
    body = [str(line) for line in body_lines] if isinstance(body_lines, list) else []
    if body:
        lines.extend(body)
    else:
        lines.extend([empty_message, ""])
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def _package_findings_json_bytes(manifest, generated_at, run_pages):
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    exported = []
    for finding in findings:
        if not isinstance(finding, dict):
            continue
        item = dict(finding)
        run_id = str(item.get("run_id") or "")
        if run_id in run_pages:
            item["run_page"] = _finding_run_anchor(item)
        exported.append(item)
    return _package_collection_json_bytes(
        "findings",
        exported,
        generated_at,
        extra={
            "assessment_context": manifest.get("assessment_context"),
            "assessment_finding_changes": manifest.get("assessment_finding_changes"),
        },
    )


def _package_findings_markdown_bytes(manifest, run_pages):
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    finding_count = len([item for item in findings if isinstance(item, dict)])
    lines = [
        "# Findings",
        "",
        f"Selected findings: {finding_count}",
        "",
    ]
    if findings:
        lines.extend([
            "| Finding | Targets | Severity | Status | Run | Evidence |",
            "| --- | --- | --- | --- | --- | --- |",
        ])
        for finding in findings:
            if not isinstance(finding, dict):
                continue
            run_id = str(finding.get("run_id") or "")
            href = f"../{_finding_run_anchor(finding)}" if run_id in run_pages else ""
            finding_label = finding.get("title") or finding.get("raw_line") or finding.get("id")
            lines.append(
                f"| {_package_markdown_link(finding_label, href)} "
                f"| {_package_markdown_text('; '.join(_package_finding_target_reference_labels(finding)))} "
                f"| {_package_markdown_text(finding.get('severity') or 'info')} "
                f"| {_package_markdown_text(finding.get('review_state') or 'new')} "
                f"| {_package_markdown_code(_package_short_id(run_id))} "
                f"| {_package_markdown_code(finding.get('raw_line') or '')}"
                f"{_package_finding_metadata_markdown(finding)} |"
            )
        lines.extend(["", "## Finding Details", ""])
        for finding in findings:
            if not isinstance(finding, dict):
                continue
            finding_label = _package_markdown_text(
                finding.get("title") or finding.get("raw_line") or finding.get("id") or "Finding"
            )
            source_line = finding.get("line_number") if finding.get("line_number") is not None else ""
            lines.extend([
                f"### {finding_label}",
                "",
                f"- ID: {_package_markdown_code(finding.get('id') or '')}",
                f"- Run: {_package_markdown_code(finding.get('run_id') or '')}",
                f"- Scope: {_package_markdown_code(finding.get('scope') or 'finding')}",
                f"- Severity: {_package_markdown_code(finding.get('severity') or 'info')}",
                f"- Review state: {_package_markdown_code(finding.get('review_state') or 'new')}",
                f"- Source line: {_package_markdown_code(source_line)}",
            ])
            target_labels = _package_finding_target_reference_labels(finding)
            if target_labels:
                lines.append("- Targets: " + "; ".join(_package_markdown_text(label) for label in target_labels))
            raw_line = str(finding.get("raw_line") or "").replace("\r\n", "\n").replace("\r", "\n").strip()
            if raw_line:
                lines.extend(["", "```text", raw_line.replace("```", "`\u200b``"), "```"])
            metadata = _package_finding_metadata_markdown(finding).replace("<br>", "\n")
            if metadata.strip():
                lines.extend(["", metadata.strip()])
            lines.append("")
    else:
        lines.append("- No selected findings.")
    return _package_collection_markdown_bytes(
        "Findings",
        None,
        lines[2:],
        empty_message="- No selected findings.",
    )


def _package_finding_target_ids(finding):
    target_ids = []
    primary = str(finding.get("target_id") or "") if isinstance(finding, dict) else ""
    if primary:
        target_ids.append(primary)
    raw_target_ids = finding.get("target_ids") if isinstance(finding, dict) else None
    if isinstance(raw_target_ids, list):
        for target_id in raw_target_ids:
            normalized = str(target_id or "")
            if normalized and normalized not in target_ids:
                target_ids.append(normalized)
    return target_ids


def _package_targets_json_bytes(manifest, generated_at):
    targets = manifest.get("targets") if isinstance(manifest.get("targets"), list) else []
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    exported = []
    for target in targets:
        if not isinstance(target, dict):
            continue
        item = dict(target)
        target_id = str(item.get("id") or "")
        finding_refs = []
        run_refs = []
        if target_id:
            for finding in findings:
                if not isinstance(finding, dict) or target_id not in _package_finding_target_ids(finding):
                    continue
                finding_id = str(finding.get("id") or "")
                run_id = str(finding.get("run_id") or "")
                if finding_id and finding_id not in finding_refs:
                    finding_refs.append(finding_id)
                if run_id and run_id not in run_refs:
                    run_refs.append(run_id)
        source_run_id = str(item.get("source_run_id") or "")
        if source_run_id and source_run_id not in run_refs:
            run_refs.append(source_run_id)
        item["finding_ids"] = finding_refs
        item["run_ids"] = run_refs
        exported.append(item)
    return _package_collection_json_bytes("targets", exported, generated_at)


def _package_targets_markdown_bytes(manifest):
    targets = manifest.get("targets") if isinstance(manifest.get("targets"), list) else []
    findings = manifest.get("findings") if isinstance(manifest.get("findings"), list) else []
    lines = ["# Targets", "", f"Selected targets: {len([item for item in targets if isinstance(item, dict)])}", ""]
    if not targets:
        lines.append("- No selected targets.")
        return _package_collection_markdown_bytes(
            "Targets",
            None,
            lines[2:],
            empty_message="- No selected targets.",
        )
    for target in targets:
        if not isinstance(target, dict):
            continue
        target_id = str(target.get("id") or "")
        raw_labels = target.get("labels")
        labels = raw_labels if isinstance(raw_labels, list) else []
        primary_label = ""
        for label in labels:
            if isinstance(label, dict) and label.get("label"):
                primary_label = str(label.get("label") or "")
                break
        target_label = _package_markdown_text(primary_label or target.get("value") or target_id or "Target")
        lines.extend([
            f"## {target_label}",
            "",
            f"- ID: {_package_markdown_code(target_id)}",
            f"- Type: {_package_markdown_code(target.get('type') or 'target')}",
            f"- Value: {_package_markdown_code(target.get('value') or '')}",
        ])
        note = target.get("note") if isinstance(target.get("note"), dict) else None
        if note and note.get("body"):
            lines.extend(["", "### Notes", "", _package_markdown_text(note.get("body") or "")])
        if labels:
            label_values = [
                _package_markdown_code(label.get("label") or "")
                for label in labels
                if isinstance(label, dict) and label.get("label")
            ]
            if label_values:
                lines.extend(["", "### Labels", "", ", ".join(label_values)])
        note = target.get("note") if isinstance(target.get("note"), dict) else None
        if note and note.get("body"):
            lines.extend(["", "### Entity Note", "", _package_markdown_text(note.get("body") or "")])
        linked_findings = [
            finding for finding in findings
            if isinstance(finding, dict) and target_id in _package_finding_target_ids(finding)
        ]
        if linked_findings:
            lines.extend(["", "### Related Findings", ""])
            for finding in linked_findings:
                finding_label = _package_markdown_text(finding.get("title") or finding.get("raw_line") or finding.get("id"))
                lines.append(f"- {finding_label} ({_package_markdown_code(finding.get('id') or '')})")
        lines.append("")
    return _package_collection_markdown_bytes(
        "Targets",
        None,
        lines[2:],
        empty_message="- No selected targets.",
    )


def _package_metadata_targets(package, manifest):
    targets = {
        "project": [str(package.get("project_id") or "")],
        "package": [str(package.get("id") or "")],
    }
    selected = manifest.get("selected_entity_ids") if isinstance(manifest.get("selected_entity_ids"), dict) else {}
    mapping = {
        "run": "run_ids",
        "finding": "finding_ids",
        "run_file_artifact": "artifact_ids",
        "target": "target_ids",
    }
    for entity_type, key in mapping.items():
        raw_ids = selected.get(key)
        if isinstance(raw_ids, list):
            targets[entity_type] = [str(value or "") for value in raw_ids if str(value or "")]
    return {
        entity_type: sorted({entity_id for entity_id in entity_ids if entity_id})
        for entity_type, entity_ids in targets.items()
        if any(entity_ids)
    }


def _metadata_items_by_entity(items):
    by_entity = {}
    for item in items:
        if not isinstance(item, dict):
            continue
        key = (str(item.get("entity_type") or ""), str(item.get("entity_id") or ""))
        if not key[0] or not key[1]:
            continue
        by_entity.setdefault(key, []).append(item)
    return by_entity


def _package_manifest_with_inline_metadata(manifest, labels, notes):
    enriched = dict(manifest)
    label_map = _metadata_items_by_entity(labels)
    note_map = _metadata_items_by_entity(notes)

    def _enrich_items(entity_type, key):
        source_items = manifest.get(key) if isinstance(manifest.get(key), list) else []
        enriched_items = []
        for source_item in source_items:
            if not isinstance(source_item, dict):
                continue
            item = dict(source_item)
            entity_id = str(item.get("id") or "")
            item_labels = label_map.get((entity_type, entity_id), [])
            item_note = note_map.get((entity_type, entity_id), [])
            if item_labels:
                item["labels"] = item_labels
            if item_note:
                item["note"] = item_note[0]
            enriched_items.append(item)
        enriched[key] = enriched_items

    _enrich_items("run", "runs")
    _enrich_items("finding", "findings")
    _enrich_items("run_file_artifact", "artifacts")
    _enrich_items("target", "targets")
    project = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}
    enriched_project = dict(project)
    project_id = str(project.get("id") or "")
    project_labels = label_map.get(("project", project_id), [])
    project_note = note_map.get(("project", project_id), [])
    if project_labels:
        enriched_project["labels"] = project_labels
    if project_note:
        enriched_project["note"] = project_note[0]
    enriched["project"] = enriched_project
    return enriched


def _package_metadata_rows(conn, session_id, table, targets, *, team_id=""):
    rows = []
    metadata_owner_sql, metadata_owner_params = _metadata_owner_where(session_id, team_id)
    for entity_type, entity_ids in targets.items():
        if not entity_ids:
            continue
        placeholders = ",".join("?" for _ in entity_ids)
        if table == "entity_labels":
            rows.extend(conn.execute(
                "SELECT id, entity_type, entity_id, label, source, created "  # nosec
                "FROM entity_labels WHERE " + metadata_owner_sql + " AND entity_type = ? "
                f"AND entity_id IN ({placeholders}) ORDER BY entity_type ASC, entity_id ASC, label ASC",
                [*metadata_owner_params, entity_type, *entity_ids],
            ).fetchall())
        elif table == "entity_notes":
            rows.extend(conn.execute(
                "SELECT id, entity_type, entity_id, body, created, updated "  # nosec
                "FROM entity_notes WHERE " + metadata_owner_sql + " AND entity_type = ? "
                f"AND entity_id IN ({placeholders}) ORDER BY entity_type ASC, entity_id ASC, updated ASC, id ASC",
                [*metadata_owner_params, entity_type, *entity_ids],
            ).fetchall())
    return rows


def _package_label_dicts(labels, redaction_rules=None):
    return [
        _redact_package_value({
            "id": row["id"],
            "entity_type": row["entity_type"],
            "entity_id": row["entity_id"],
            "label": row["label"],
            "source": row["source"],
            "created": row["created"],
        }, redaction_rules)
        for row in labels
    ]


def _package_labels_json_bytes(labels, generated_at, redaction_rules=None):
    exported = _package_label_dicts(labels, redaction_rules)
    return _package_collection_json_bytes("labels", exported, generated_at)


def _package_note_dicts(notes, redaction_rules=None):
    return [
        _redact_package_value({
            "id": row["id"],
            "entity_type": row["entity_type"],
            "entity_id": row["entity_id"],
            "body": row["body"],
            "created": row["created"],
            "updated": row["updated"],
        }, redaction_rules)
        for row in notes
    ]


def _package_notes_json_bytes(notes, generated_at, *, included, redaction_rules=None):
    exported = _package_note_dicts(notes, redaction_rules)
    return _package_collection_json_bytes(
        "notes",
        exported,
        generated_at,
        extra={"include_private_notes": bool(included)},
    )


def _package_project_notes_markdown_bytes(manifest, generated_at):
    project = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}
    project_notes = _package_markdown_text(_entity_note_body(project))
    lines = []
    if project_notes:
        lines.extend([project_notes, ""])
    else:
        lines.extend(["No project notes were included in this package.", ""])
    return _package_collection_markdown_bytes(
        f"{project.get('name') or 'Project'} Notes",
        generated_at,
        lines,
        empty_message="No project notes were included in this package.",
    )


def _package_notes_markdown_bytes(notes, generated_at, *, included):
    lines = []
    if not included:
        return _package_collection_markdown_bytes(
            "Entity Notes",
            generated_at,
            ["Private entity notes were excluded from this package.", ""],
            empty_message="Private entity notes were excluded from this package.",
        )
    if not notes:
        return _package_collection_markdown_bytes(
            "Entity Notes",
            generated_at,
            ["No selected entity notes were included in this package.", ""],
            empty_message="No selected entity notes were included in this package.",
        )

    for note in notes:
        if not isinstance(note, dict):
            continue
        entity_type = _package_markdown_text(note.get("entity_type") or "entity")
        entity_id = _package_markdown_code(_package_short_id(note.get("entity_id")))
        updated = _package_markdown_text(note.get("updated") or note.get("created") or "unknown")
        body = _package_markdown_text(note.get("body") or "")
        lines.extend([
            f"## {entity_type} {entity_id}",
            "",
            f"- Updated: {updated}",
            "",
            body or "_No note body._",
            "",
        ])
    return _package_collection_markdown_bytes(
        "Entity Notes",
        generated_at,
        lines,
        empty_message="No selected entity notes were included in this package.",
    )
